# Generated by Django 3.2.15 on 2022-08-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="media/images/default.jpg", upload_to="images/"
            ),
        ),
    ]
